on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
   
      
      - uses: actions/checkout@v3

      - name: "login to Dockerhub"
        run: docker login --username basantsalama --password dckr_pat_wTaQv6jW4R0uRucQGCHMJcp-8cU
     
    
      

      

   
