on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
   
      
      - uses: actions/checkout@v3
        env:
          DOCKER_USER: ${{ secrets.DOCKERUSERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}

          run: |
             docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
     
    
      

      

   
